[project]
name = "atri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx[http2]>=0.28.1",
    "jieba>=0.42.1",
    "mcp>=1.12.2",
    "openai>=1.82.0",
    "pymilvus>=2.5.14",
]

[tool.uv.workspace]
members = [
    "abandoned/MCP_test/mcp-client",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
