[project]
name = "atri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jieba>=0.42.1",
    "mcp>=1.6.0",
    "openai>=1.82.0",
]

[tool.uv.workspace]
members = [
    "abandoned/MCP_test/mcp-client",
]
